<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Department;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $departments = [
            "Accounting Section - Finance Division",
            "Accounting Section, Finance Division - Dagupan Campus",
            "Accounting Section, Finance Division - Rizal Campus",
            "Administrative Council",
            "Administrative Services Division",
            "Agri-Based IGP - Cattle Production",
            "Agri-Based IGP - Egg Production",
            "Agri-Based IGP - Goat Production",
            "Agri-Based IGP - Rice Production",
            "Agri-Based IGP - Swine Production",
            "Alcohol Production",
            "Analytic Laboratory",
            "Breeding and Insimination Facility",
            "Budget Section - Finance Division",
            "Budget Section, Finance Division - Dagupan Campus",
            "Budget Section, Finance Division - Rizal Campus",
            "Business Affairs Office",
            "Business Affairs Office - Agri-Based IGP",
            "Business Affairs Office - Auxiliary Services",
            "Business Affairs Office - Non-Agri-Based IGP",
            "Business Affairs Office (BAO)",
            "Campus-Based Kalinga Cultural Heritage Studies & Edu-Tourism Centre",
            "Cashiering Section - Finance Division",
            "Cashiering Section, Finance Division - Dagupan Campus",
            "Cashiering Section, Finance Division - Rizal Campus",
            "Center for Training and Professional Development",
            "Center for Training and Professional Education",
            "Center for Watershed Management",
            "Central Science Laboratory Services Office",
            "Central Student Government",
            "Coffee Research Center",
            "College of Advanced Studies",
            "College of Advanced Studies-Extension",
            "College of Advanced Studies-Research",
            "College of Agriculture",
            "College of Agriculture - Extension and Training Services",
            "College of Agriculture - HEIRLOOM Corn Project",
            "College of Agriculture - Research and Development Services",
            "College of Agro-Forestry and Environmental Sciences",
            "College of Agro-Forestry and Environmental Sciences - Extension and Training Services",
            "College of Agro-Forestry and Environmental Sciences - Research and Development Services",
            "College of Agroforestry and Environmental Studies",
            "College of Business Administration and Accountancy",
            "College of Business Administration and Accountancy - Extension and Training Services",
            "College of Business Administration and Accountancy - Research and Development Services",
            "College of Criminal Justice Education",
            "College of Criminal Justice Education - Extension and Training Services",
            "College of Criminal Justice Education - Research and Development Services",
            "College of Education",
            "College of Education - Extension and Training Services",
            "College of Education - Research and Development Services",
            "College of Education and Information Technology",
            "College of Engineering and Information Technology",
            "College of Engineering and Information Technology - Computer Engineering Laboratory",
            "College of Engineering and Information Technology - Extension and Training Services",
            "College of Engineering and Information Technology - Research and Development Services",
            "College of Entrepreneurship, Tourism and Hospitality Management",
            "College of Entrepreneurship, Tourism and Hotel Management",
            "College of Entrepreneurship, Tourism and Hotel Management - Extension and Training Services",
            "College of Entrepreneurship, Tourism and Hotel Management - Research and Development Services",
            "College of Forestry",
            "College of Forestry - Extension and Training Services",
            "College of Forestry - Research and Development Services",
            "College of Health and Natural Sciences",
            "College of Health and Natural Sciences - Birthing Clinic",
            "College of Health and Natural Sciences - Extension and Training Services",
            "College of Health and Natural Sciences - Research and Development Services",
            "College of Law",
            "College of Law - Extension and Training Services",
            "College of Law - Research and Development Services",
            "College of Liberal Arts and Social Sciences",
            "College of Liberal Arts and Social Sciences - Extension and Training Services",
            "College of Liberal Arts and Social Sciences - Research and Development Services",
            "College of Public Administration and Indigenous Governance",
            "College of Public Administration and Indigenous Governance - Extension and Training Services",
            "College of Public Administration and Indigenous Governance - Research and Development Services",
            "Commission on Audit",
            "Counselling, Testing and Placement Services - Bulanao Campus",
            "Counselling, Testing and Placement Services - Dagupan Campus",
            "Counselling, Testing and Placement Services - Laboratory High School",
            "Counselling, Testing and Placement Services - Rizal Campus",
            "Dental Services Office",
            "Department of Information Technology",
            "Department of Languages",
            "Department of Mathematics",
            "Department of Natural Sciences",
            "Department of Physical Education",
            "Department of Social Sciences",
            "Finance / Accounting Office",
            "Finance Management Services Division",
            "Food Processing and Innovation Research Center",
            "Futures Thinking and Strategic Foresight",
            "Gender and Development",
            "General Service Office",
            "General Services Office",
            "General Services Office (GSO)",
            "Graduate School",
            "Guidance and Counseling",
            "Hotel and Restaurant Management (HRM) Hostel",
            "HRM Bldg. Compound - Water Resources Facility",
            "Human Resource Management Office - Bulanao Campus",
            "Human Resource Management Office - Dagupan Campus",
            "Human Resource Management Office - Rizal Campus",
            "Human Resource Management Office (HRMO)",
            "ICT Office",
            "Information and Communications Technology Center",
            "Internal Control Unit",
            "KALINGA DINAYAO RESEARCH CENTER",
            "Kalinga National High School Faculty",
            "KSU Center for International Languages",
            "KSU Gymnasium",
            "KSU-DOST CLEARS PROJECT",
            "KSU-DOST GIA (BOONDOCK)",
            "KSU-MAKILALA MINING Env'l Baseline Studies",
            "KSU-OFFICE OF PRESIDENTIAL ADVISER ON THE PEACE PROCESS",
            "KSU-TESDA Project",
            "Laboratory High School",
            "Laboratory High School - Extension and Training Services",
            "Laboratory High School - Research and Development Services",
            "LADIES DORMITORY-RIZAL CAMPUS",
            "Legal Unit",
            "Library",
            "Medical and Dental Clinic",
            "Medical Services Office",
            "Mushroom Production Facility-Bulanao Campus",
            "Mushroom Research Facility",
            "Office of the Alumni Affairs and Services",
            "Office of the Board/University Secretary",
            "Office of the Campus Administrator - Bulanao Campus",
            "Office of the Campus Administrator - Dagupan Campus",
            "Office of the Campus Administrator - Rizal Campus",
            "Office of the Income Generating Projects Services",
            "Office of the Library Services - Dagupan Campus",
            "Office of the Library Services - Laboratory High School",
            "Office of the Library Services - Main Campus",
            "Office of the Library Services - Rizal Campus",
            "Office of the NSTP Services",
            "Office of the Open Distance Education, Transnational Education and International Learning",
            "Office of the President",
            "Office of the Scholarship Services",
            "Office of the Sports and Socio-Cultural Affairs",
            "Office of the Student Development Services and Placement Services",
            "Office of the Supervisor for Special Projects",
            "Office of the University Extension and Training Services",
            "Office of the University President",
            "Office of the University Registrar",
            "Office of the University Research and Development",
            "Office of the Vice President for Academic Affairs",
            "Office of the Vice President for Academic and Student Development",
            "Office of the Vice President for Administration and Finance",
            "Office of the Vice President for Research and Development, Extension and Training",
            "Office of the Vice President for Research, Extension and Development",
            "Payroll Section - Finance Division",
            "Performing Arts Theater",
            "Planning and Strategy Office",
            "PMO- Bids and Award Committee",
            "Procurement Management Office",
            "Procurement Management Office - Dagupan Campus",
            "Procurement Management Office - Rizal Campus",
            "Project Management Unit",
            "Quality Assurance Office",
            "Records and Archives Office",
            "Records and Archives Section - Dagupan Campus",
            "Records and Archives Section - Rizal Campus",
            "Registrar",
            "Research and Development, Extension and Training Hostel",
            "Research and Extension Office",
            "Rizal Campus - Computer Laboratory",
            "Rizal Campus - Sericulture Research Program",
            "Security Services-Bulanao Campus",
            "Security Services-Dagupan Campus",
            "Security Services-Rizal Campus",
            "Sentro ng Wika at Kultura",
            "Student Internship Abroad Program (SIAP) Services",
            "Student Publication (EARTHLINE)",
            "Supply and Property Management Office - Bulanao Campus",
            "Supply and Property Management Office - Dagupan Campus",
            "Supply and Property Management Office - Rizal Campus",
            "Supply Procurement Office",
            "Supreme Student Council - Bulanao Campus",
            "Supreme Student Council - Dagupan Campus",
            "Supreme Student Council - Rizal Campus",
            "Technology and Innovation",
            "University Disaster Risk Reduction Management",
            "University Environmental Management Committee",
            "University Information Office - AWONG Publication",
        ];

        foreach ($departments as $department) {
            Department::firstOrCreate([
                'name' => $department,
            ]);
        }
    }
}
