version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ict-helpdesk-app
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - ict-net

  webserver:
    image: nginx:alpine
    container_name: ict-helpdesk-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - ict-net

  certbot:
    image: certbot/certbot
    container_name: ict-helpdesk-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # entrypoint: /bin/sh

networks:
  ict-net:
    driver: bridge
